version: 2
sources:
  - name: source_dbt
    database: |   
      {%- if target.name.lower() == "dev" -%} DB_DBT_SGAIDE_DEV 
      {%- elif target.name.lower() == "prod" -%} DB_DBT_SGAIDE_PROD
      {%- else -%} DB_DBT_SGAIDE_DEV
      {%- endif -%}


    schema: source
    tables:
      - name: restaurants
        description: Table contenant des infos sur les différents restaurants
        columns:
          - name: IDENTIFIER
            tests:
            - unique
            - not_null
              

      - name: orders
        description: Table contenant des infos sur les différentes commandes
        columns:
          - name: RESTAURANT_IDENTIFIER
            tests:
            - not_null
      
      - name: dishes
     
      
