version: 2

sources:
  - name: source
    database: |
      {%- if target.name.lower() == "dev" -%} DB_DBT_SGAIDE_DEV
      {%- elif target.name.lower() == "prod" -%} DB_DBT_SGAIDE_PROD
      {%- else -%} DB_DBT_SGAIDE_DEV
      {%- endif -%}
    schema: source
    
    tables:
      - name: restaurants
        columns:
        - name: open_on_sunday
        - name: address
          tests:
            - not_null  
      - name: orders
        columns:
        - name: identifier
          tests:
          - unique
        - name: restaurant_identifier
      - name: dishes
